name: Golang

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Tidy
      run: make tidy

    - name: Vet
      run: make vet

    - name: Format
      run: make fmt

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build